name: Static checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gdscript:
    name: GDScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GDScript Toolkit
        uses: Scony/godot-gdscript-toolkit@master

      - name: Check GDScript formatting
        run: gdformat --check godot/scripts/

      - name: Lint GDScript
        run: gdlint godot/scripts/

  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust components
        run: rustup component add rustfmt clippy

      - name: Check Rust formatting
        run: cargo fmt --manifest-path rust/Cargo.toml -- --check

      - name: Check Rust
        run: cargo check --manifest-path rust/Cargo.toml

      - name: Lint Rust
        run: cargo clippy --manifest-path rust/Cargo.toml --all-targets -- -D warnings
